services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: chatbot
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d chatbot"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_URL: postgresql://myuser:mypassword@db:5432/chatbot
      AUTH_SECRET: development_auth_secret
      OPENAI_API_KEY: dummy_key
      KAMIWAZA_URI: https://prod.kamiwaza.ai/api
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: